/**
 * utils/reportGenerator.js
 * Generate structured text / JSON reports from analysis data
 */

const { formatINR, round, generateReportId } = require('./helpers');

/**
 * Build a comprehensive text summary report
 */
function buildTextReport(reportData) {
  const { emissions, carbonSinks, gapAnalysis, pathways, carbonCredits, summary } = reportData;
  const id = generateReportId();
  const date = new Date().toLocaleDateString('en-IN', { dateStyle: 'long' });

  const lines = [
    '═══════════════════════════════════════════════════════════',
    '     COALCARBON IQ — CARBON NEUTRALITY ASSESSMENT REPORT',
    '═══════════════════════════════════════════════════════════',
    `Report ID   : ${id}`,
    `Generated   : ${date}`,
    `Mine Name   : ${summary.mineName || 'N/A'}`,
    `State       : ${(summary.state || '').replace(/_/g, ' ')}`,
    `Mine Type   : ${summary.mineType}`,
    '',
    '─── EMISSION SUMMARY ───────────────────────────────────────',
    `Total Emissions     : ${round(summary.totalEmissions_tCO2e, 0).toLocaleString('en-IN')} tCO₂e/year`,
    `  ├ Scope 1 (Direct)       : ${round(emissions.totals.scope1, 0).toLocaleString('en-IN')} tCO₂e`,
    `  ├ Scope 2 (Electricity)  : ${round(emissions.totals.scope2, 0).toLocaleString('en-IN')} tCO₂e`,
    `  ├ Scope 3 (Transport)    : ${round(emissions.totals.scope3, 0).toLocaleString('en-IN')} tCO₂e`,
    `  └ Fugitive (CH₄)         : ${round(emissions.totals.fugitive, 0).toLocaleString('en-IN')} tCO₂e`,
    '',
    `Per Worker Emission : ${round(summary.perWorker_tCO2e, 2)} tCO₂e/worker/year`,
    `Emission Intensity  : ${round(summary.perTonneCoal_tCO2e, 4)} tCO₂e/tonne coal`,
    '',
    '─── CARBON SINKS ───────────────────────────────────────────',
    `Total Carbon Sinks  : ${round(summary.totalSinks_tCO2e, 0).toLocaleString('en-IN')} tCO₂e/year`,
    `Sink Coverage       : ${round(summary.coveragePercent, 1)}%`,
    '',
    '─── GAP ANALYSIS ───────────────────────────────────────────',
    `Carbon Neutrality Gap : ${round(gapAnalysis.gap, 0).toLocaleString('en-IN')} tCO₂e/year`,
    `Status                : ${gapAnalysis.status}`,
    `Afforestation Needed  : ${round(gapAnalysis.afforestationNeededHa, 0).toLocaleString('en-IN')} hectares`,
    `Estimated Cost        : ${formatINR(gapAnalysis.estimatedAfforestationCost)}`,
    '',
    '─── BEST PATHWAY ───────────────────────────────────────────',
    `Strategy       : ${pathways.combined?.name || 'Combined Strategy'}`,
    `Reduction      : ${round(pathways.combined?.reduction_pct || 0, 1)}%`,
    `Capital Cost   : ${formatINR(pathways.combined?.capex_inr)}`,
    `Timeline       : ${pathways.combined?.timeline || 'N/A'}`,
    '',
    '─── CARBON CREDIT POTENTIAL ────────────────────────────────',
    `Credits Earnable      : ${round(carbonCredits.creditsEarnable, 0).toLocaleString('en-IN')} tCO₂e`,
    `VCS Revenue           : ${formatINR(carbonCredits.markets?.vcs?.revenue_inr)} /year`,
    `Gold Standard Revenue : ${formatINR(carbonCredits.markets?.gold_standard?.revenue_inr)} /year`,
    `Indian Carbon Market  : ${formatINR(carbonCredits.markets?.indian_carbon_market?.revenue_inr)} /year`,
    '',
    '─── PRIORITY RECOMMENDATIONS ───────────────────────────────',
    ...(gapAnalysis.recommendations || []).map((r, i) =>
      `${i + 1}. [${r.priority}] ${r.category}: ${r.action}`
    ),
    '',
    '═══════════════════════════════════════════════════════════',
    '  Generated by CoalCarbon IQ | India Carbon Intelligence',
    '═══════════════════════════════════════════════════════════'
  ];

  return { id, text: lines.join('\n'), date };
}

/**
 * Build CSV export of emission breakdown
 */
function buildCSVReport(reportData) {
  const { emissions, carbonSinks, gapAnalysis } = reportData;
  const rows = [
    ['Category', 'Scope', 'Activity', 'tCO2e/year', 'Percentage'],
    ...Object.values(emissions.scope1 || {}).map(v => [
      'Direct Emissions', 'Scope 1', v.label, round(v.emission / 1000, 2), round(v.emission / 1000 / emissions.totals.total * 100, 2)
    ]),
    ...Object.values(emissions.scope2 || {}).map(v => [
      'Indirect Emissions', 'Scope 2', v.label, round(v.emission / 1000, 2), round(v.emission / 1000 / emissions.totals.total * 100, 2)
    ]),
    ...Object.values(emissions.scope3 || {}).map(v => [
      'Value Chain', 'Scope 3', v.label, round(v.emission / 1000, 2), round(v.emission / 1000 / emissions.totals.total * 100, 2)
    ]),
    ...Object.values(emissions.fugitive || {}).map(v => [
      'Fugitive Emissions', 'Fugitive', v.label, round(v.emission / 1000, 2), round(v.emission / 1000 / emissions.totals.total * 100, 2)
    ]),
    ['', '', '', '', ''],
    ['TOTAL EMISSIONS', '', '', round(emissions.totals.total, 2), '100.00'],
    ['TOTAL SINKS', '', '', round(carbonSinks.totalSink, 2), ''],
    ['NET GAP', '', '', round(gapAnalysis.gap, 2), '']
  ];

  return rows.map(row => row.join(',')).join('\n');
}

module.exports = { buildTextReport, buildCSVReport };
